apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: duck
spec:
  version: {{ .TagName }}
  homepage: https://github.com/n3wscott/kubectl-duck
  shortDescription: List custom resources with ducktype support
  description: |
    This plugin allows you to list and get custom resources based on ducktype
    labels on CRDs.
  caveats: |
    * Ducktype labels are currenly hardcoded to known types from Knative.
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/n3wscott/kubectl-duck/releases/download/{{ .TagName }}/kubectl-duck_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    bin: kubectl-duck
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/n3wscott/kubectl-duck/releases/download/{{ .TagName }}/kubectl-duck_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    files:
    bin: kubectl-duck
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/n3wscott/kubectl-duck/releases/download/{{ .TagName }}/kubectl-duck_{{ .TagName }}_windows_amd64.tar.gz" .TagName }}
    bin: kubectl-duck.exe
